apiVersion: apps/v1
kind: Deployment
metadata:
  name: openfga
  namespace: epalika
  labels:
    app: openfga
    component: authorization
spec:
  replicas: 2
  selector:
    matchLabels:
      app: openfga
  template:
    metadata:
      labels:
        app: openfga
        component: authorization
    spec:
      containers:
      - name: openfga
        image: openfga/openfga:v1.5.0
        args:
        - "run"
        - "--datastore-engine=memory"
        - "--log-format=json"
        - "--http-addr=0.0.0.0:8080"
        ports:
        - containerPort: 8080
          name: http
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
---
apiVersion: v1
kind: Service
metadata:
  name: openfga
  namespace: epalika
  labels:
    app: openfga
spec:
  selector:
    app: openfga
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP