apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: epalika-prod

namespace: epalika-prod

bases:
- ../../base

namePrefix: prod-

commonLabels:
  environment: production

patchesStrategicMerge:
- namespace-patch.yaml
- replica-patch.yaml
- resources-patch.yaml
- security-patch.yaml
- ingress-patch.yaml

configMapGenerator:
- name: epalika-config-prod
  literals:
  - fga-check-url=http://openfga:8080/stores/$(FGA_STORE)/check
  - keycloak-url=http://keycloak:8080
  - keycloak-realm=epalika
  - environment=production
  - log-level=info

# Note: In production, secrets should be managed externally
# secretGenerator:
# - name: epalika-secrets-prod
#   files:
#   - secrets/fga-store-id
#   - secrets/fga-model-id
#   - secrets/keycloak-client-secret

images:
- name: epalika/pdp
  newTag: v1.0.0
- name: epalika/darta-chalani
  newTag: v1.0.0