apiVersion: apps/v1
kind: Deployment
metadata:
  name: oathkeeper
  namespace: epalika
  labels:
    app: oathkeeper
    component: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: oathkeeper
  template:
    metadata:
      labels:
        app: oathkeeper
        component: api-gateway
    spec:
      containers:
      - name: oathkeeper
        image: oryd/oathkeeper:v0.40.7
        args:
        - "serve"
        - "--config"
        - "/etc/config/oathkeeper.yaml"
        ports:
        - containerPort: 4455
          name: proxy
        - containerPort: 4456
          name: api
        livenessProbe:
          httpGet:
            path: /health/alive
            port: 4456
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 4456
          initialDelaySeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        securityContext:
          runAsNonRoot: true
          runAsUser: 1000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        volumeMounts:
        - name: config
          mountPath: /etc/config
          readOnly: true
        - name: rules
          mountPath: /rules
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: oathkeeper-config
      - name: rules
        configMap:
          name: oathkeeper-rules
---
apiVersion: v1
kind: Service
metadata:
  name: oathkeeper
  namespace: epalika
  labels:
    app: oathkeeper
spec:
  selector:
    app: oathkeeper
  ports:
  - port: 4455
    targetPort: 4455
    name: proxy
  - port: 4456
    targetPort: 4456
    name: api
  type: ClusterIP