apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: epalika-services
  namespace: epalika
  labels:
    app: epalika
    component: monitoring
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: epalika
  endpoints:
  - port: http
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
  - port: management
    path: /metrics
    interval: 30s
    scrapeTimeout: 10s
---
apiVersion: v1
kind: Service
metadata:
  name: pdp-metrics
  namespace: epalika
  labels:
    app: pdp
    component: metrics
spec:
  selector:
    app: pdp
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  type: ClusterIP
---
apiVersion: v1
kind: Service  
metadata:
  name: darta-chalani-metrics
  namespace: epalika
  labels:
    app: darta-chalani
    component: metrics
spec:
  selector:
    app: darta-chalani
  ports:
  - port: 9000
    targetPort: 9000
    name: http
  type: ClusterIP