serve:
  proxy:
    port: 4455
    host: 0.0.0.0
  api:
    port: 4456
    host: 0.0.0.0

access_rules:
  repositories:
    - file:///oathkeeper/base/health-check.json
    - file:///oathkeeper/rules/darta-chalani.json

authenticators:
  jwt:
    enabled: true
    config:
      jwks_urls:
        - http://keycloak:8080/realms/{palika,palika_*}/protocol/openid-connect/certs
        - http://localhost:8083/realms/{palika,palika_*}/protocol/openid-connect/certs
      scope_strategy: exact
      trusted_issuers:
        - http://keycloak:8080/realms/palika
        - http://keycloak:8080/realms/palika_sallaghari
        - http://localhost:8083/realms/palika
        - http://localhost:8083/realms/palika_sallaghari
      claims_mapper_url: ""
      required_scope: []

  noop:
    enabled: true

authorizers:
  remote_json:
    enabled: true
    config:
      remote: http://pdp:8080/authorize
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ .MatchContext.URL.Path }}",
          "action": "{{ .MatchContext.Method }}",
          "tenant": "{{ if .Extra.tenant_id }}{{ index .Extra.tenant_id 0 }}{{ else }}palika{{ end }}"
        }
      headers:
        Content-Type: application/json

  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User-ID: "{{ print .Subject }}"
        X-Tenant: "{{ if .Extra.tenant_id }}{{ index .Extra.tenant_id 0 }}{{ else }}palika{{ end }}"

  noop:
    enabled: true

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true

log:
  level: debug
  format: json
