serve:
  proxy:
    port: 4455
    host: 0.0.0.0
  api:
    port: 4456
    host: 0.0.0.0

access_rules:
  repositories:
    - file:///policies/oathkeeper/base

authenticators:
  jwt:
    enabled: true
    config:
      jwks_urls:
        - http://keycloak:8083/realms/palika/protocol/openid-connect/certs
      allowed_issuers:
        - http://keycloak:8083/realms/palika
      required_scope: ["openid"]
      target_audience:
        - palika-api
      cache:
        enabled: true
        ttl: 60s

  noop:
    enabled: true

authorizers:
  remote_json:
    enabled: true
    config:
      remote: http://pdp:8080/authorize
      timeout: 2s
      headers:
        Content-Type: application/json

  allow:
    enabled: true

mutators:
  header:
    enabled: true
    config:
      headers:
        X-User-ID: "{{ print .Subject }}"
        X-Roles: '{{ join .Extra.roles "," }}'
        X-Tenant: "{{ .Extra.tenant }}"
        Accept-Language: "{{ .Extra.locale }}"
        X-Request-ID: "{{ printUUID }}"
        Traceparent: "{{ .Extra.traceparent }}"

  noop:
    enabled: true

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true

upstream:
  preserve_host: true
  timeout: 30s

log:
  level: debug
  format: json
