serve:
  proxy:
    port: 4455
    host: 0.0.0.0
  api:
    port: 4456
    host: 0.0.0.0

access_rules:
  repositories:
    - file:///oathkeeper/base/health-check.json
    - file:///oathkeeper/rules/darta-chalani.json

authenticators:
  jwt:
    enabled: true
    config:
      jwks_urls:
        - file:///etc/secrets/keycloak_${KEYCLOAK_REALM}.jwks.json
      scope_strategy: exact
      trusted_issuers:
        - http://keycloak:8083/realms/${KEYCLOAK_REALM}
        - http://172.17.0.1:8083/realms/${KEYCLOAK_REALM}
      required_scope: []

  noop:
    enabled: true

authorizers:
  remote_json:
    enabled: true
    config:
      remote: ${PDP_URL}
      payload: |
        {
          "subject": "{{ print .Subject }}",
          "resource": "{{ .MatchContext.URL.Path }}",
          "action": "{{ .MatchContext.Method }}",
          "tenant": "{{ if .Extra.tenant_id }}{{ index .Extra.tenant_id 0 }}{{ else }}palika{{ end }}"
        }
      headers:
        Content-Type: application/json

  allow:
    enabled: true

mutators:
  id_token:
    enabled: true
    config:
      issuer_url: http://localhost:4455
      jwks_url: file:///oathkeeper/secrets/mutator.id_token.jwks.json
      ttl: 1m

  header:
    enabled: true
    config:
      headers:
        X-User-ID: "{{ print .Subject }}"
        X-Tenant: "{{ if .Extra.tenant_id }}{{ index .Extra.tenant_id 0 }}{{ else }}palika{{ end }}"

  noop:
    enabled: true

errors:
  fallback:
    - json
  handlers:
    json:
      enabled: true
      config:
        verbose: true

log:
  level: debug
  format: text
  leak_sensitive_values: true
