// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CountDartas(ctx context.Context) (int64, error)
	CreateDarta(ctx context.Context, arg CreateDartaParams) (Darta, error)
	GetDarta(ctx context.Context, id uuid.UUID) (Darta, error)
	ListDartas(ctx context.Context, arg ListDartasParams) ([]Darta, error)
	UpdateDartaStatus(ctx context.Context, arg UpdateDartaStatusParams) (Darta, error)
}

var _ Querier = (*Queries)(nil)
