// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// ============================================================================
	// CHALANI ATTACHMENTS
	// ============================================================================
	AddChalaniAttachment(ctx context.Context, arg AddChalaniAttachmentParams) error
	// ============================================================================
	// CHALANI SIGNATORIES
	// ============================================================================
	AddChalaniSignatory(ctx context.Context, arg AddChalaniSignatoryParams) (ChalaniSignatory, error)
	// ============================================================================
	// DARTA ANNEXES - Additional attachments
	// ============================================================================
	AddDartaAnnex(ctx context.Context, arg AddDartaAnnexParams) error
	// ============================================================================
	// DARTA RELATIONSHIPS - Related dartas
	// ============================================================================
	AddDartaRelationship(ctx context.Context, arg AddDartaRelationshipParams) error
	CheckAllSignatoriesApproved(ctx context.Context, chalaniID pgtype.UUID) (CheckAllSignatoriesApprovedRow, error)
	CloseChalani(ctx context.Context, id uuid.UUID) (Chalani, error)
	CloseDarta(ctx context.Context, id uuid.UUID) (Darta, error)
	CountApplicants(ctx context.Context, arg CountApplicantsParams) (int64, error)
	CountAttachments(ctx context.Context, tenantID string) (int64, error)
	CountAuditEntries(ctx context.Context, arg CountAuditEntriesParams) (int64, error)
	CountChalaniTemplates(ctx context.Context, arg CountChalaniTemplatesParams) (int64, error)
	CountChalanis(ctx context.Context, arg CountChalanisParams) (int64, error)
	CountDartas(ctx context.Context, arg CountDartasParams) (int64, error)
	CountMyDartas(ctx context.Context, arg CountMyDartasParams) (int64, error)
	CountRecipients(ctx context.Context, arg CountRecipientsParams) (int64, error)
	// ============================================================================
	// APPLICANTS - People/Organizations submitting darta
	// ============================================================================
	CreateApplicant(ctx context.Context, arg CreateApplicantParams) (Applicant, error)
	// ============================================================================
	// ATTACHMENTS - File attachments
	// ============================================================================
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (Attachment, error)
	// ============================================================================
	// AUDIT TRAIL
	// ============================================================================
	CreateAuditEntry(ctx context.Context, arg CreateAuditEntryParams) (AuditTrail, error)
	// ============================================================================
	// CHALANIS - Outgoing correspondence
	// ============================================================================
	CreateChalani(ctx context.Context, arg CreateChalaniParams) (Chalani, error)
	// ============================================================================
	// CHALANI APPROVALS
	// ============================================================================
	CreateChalaniApproval(ctx context.Context, arg CreateChalaniApprovalParams) (ChalaniApproval, error)
	// ============================================================================
	// CHALANI TEMPLATES
	// ============================================================================
	CreateChalaniTemplate(ctx context.Context, arg CreateChalaniTemplateParams) (ChalaniTemplate, error)
	// ============================================================================
	// DARTAS - Incoming correspondence (main queries)
	// ============================================================================
	CreateDarta(ctx context.Context, arg CreateDartaParams) (Darta, error)
	// ============================================================================
	// RECIPIENTS - People/Organizations receiving chalani
	// ============================================================================
	CreateRecipient(ctx context.Context, arg CreateRecipientParams) (Recipient, error)
	DeleteApplicant(ctx context.Context, id uuid.UUID) error
	DeleteAttachment(ctx context.Context, id uuid.UUID) error
	DeleteChalaniTemplate(ctx context.Context, id uuid.UUID) error
	DeleteRecipient(ctx context.Context, id uuid.UUID) error
	FindApplicantByIdentification(ctx context.Context, identificationNumber *string) (Applicant, error)
	FindRecipientByContact(ctx context.Context, arg FindRecipientByContactParams) (Recipient, error)
	GetAcknowledgementRate(ctx context.Context, arg GetAcknowledgementRateParams) (GetAcknowledgementRateRow, error)
	GetApplicant(ctx context.Context, id uuid.UUID) (Applicant, error)
	GetApplicantByEmailOrPhone(ctx context.Context, arg GetApplicantByEmailOrPhoneParams) (Applicant, error)
	GetAttachment(ctx context.Context, id uuid.UUID) (Attachment, error)
	GetAttachmentByChecksum(ctx context.Context, arg GetAttachmentByChecksumParams) (Attachment, error)
	GetAttachmentsByIDs(ctx context.Context, dollar_1 []pgtype.UUID) ([]Attachment, error)
	GetAuditTrail(ctx context.Context, arg GetAuditTrailParams) ([]AuditTrail, error)
	GetAuditTrailByEntity(ctx context.Context, arg GetAuditTrailByEntityParams) ([]AuditTrail, error)
	GetAuditTrailByUser(ctx context.Context, arg GetAuditTrailByUserParams) ([]AuditTrail, error)
	GetChalani(ctx context.Context, id uuid.UUID) (GetChalaniRow, error)
	GetChalaniApproval(ctx context.Context, id uuid.UUID) (ChalaniApproval, error)
	GetChalaniApprovals(ctx context.Context, chalaniID pgtype.UUID) ([]GetChalaniApprovalsRow, error)
	GetChalaniAttachments(ctx context.Context, chalaniID pgtype.UUID) ([]Attachment, error)
	GetChalaniByIdempotencyKey(ctx context.Context, arg GetChalaniByIdempotencyKeyParams) (Chalani, error)
	GetChalaniByNumber(ctx context.Context, arg GetChalaniByNumberParams) (GetChalaniByNumberRow, error)
	GetChalaniSignatories(ctx context.Context, chalaniID pgtype.UUID) ([]ChalaniSignatory, error)
	GetChalaniSignatory(ctx context.Context, id uuid.UUID) (ChalaniSignatory, error)
	GetChalaniSimple(ctx context.Context, id uuid.UUID) (Chalani, error)
	GetChalaniStatsByChannel(ctx context.Context, arg GetChalaniStatsByChannelParams) ([]GetChalaniStatsByChannelRow, error)
	// Statistics
	GetChalaniStatsByStatus(ctx context.Context, arg GetChalaniStatsByStatusParams) ([]GetChalaniStatsByStatusRow, error)
	GetChalaniTemplate(ctx context.Context, id uuid.UUID) (ChalaniTemplate, error)
	GetDarta(ctx context.Context, id uuid.UUID) (GetDartaRow, error)
	GetDartaAnnexes(ctx context.Context, dartaID pgtype.UUID) ([]Attachment, error)
	GetDartaByIdempotencyKey(ctx context.Context, arg GetDartaByIdempotencyKeyParams) (Darta, error)
	GetDartaByNumber(ctx context.Context, arg GetDartaByNumberParams) (GetDartaByNumberRow, error)
	GetDartaSimple(ctx context.Context, id uuid.UUID) (Darta, error)
	GetDartaStatsByChannel(ctx context.Context, arg GetDartaStatsByChannelParams) ([]GetDartaStatsByChannelRow, error)
	// Statistics queries
	GetDartaStatsByStatus(ctx context.Context, arg GetDartaStatsByStatusParams) ([]GetDartaStatsByStatusRow, error)
	GetMyChalani(ctx context.Context, arg GetMyChalaniParams) ([]GetMyChalaniRow, error)
	GetMyDartas(ctx context.Context, arg GetMyDartasParams) ([]GetMyDartasRow, error)
	GetNextChalaniNumber(ctx context.Context, arg GetNextChalaniNumberParams) (int32, error)
	GetNextDartaNumber(ctx context.Context, arg GetNextDartaNumberParams) (int32, error)
	GetOverdueCount(ctx context.Context, arg GetOverdueCountParams) (int64, error)
	GetRecipient(ctx context.Context, id uuid.UUID) (Recipient, error)
	GetRelatedDartas(ctx context.Context, dartaID pgtype.UUID) ([]GetRelatedDartasRow, error)
	ListApplicants(ctx context.Context, arg ListApplicantsParams) ([]Applicant, error)
	ListAttachments(ctx context.Context, arg ListAttachmentsParams) ([]Attachment, error)
	ListAttachmentsByUploader(ctx context.Context, arg ListAttachmentsByUploaderParams) ([]Attachment, error)
	ListChalaniTemplates(ctx context.Context, arg ListChalaniTemplatesParams) ([]ChalaniTemplate, error)
	// List with filtering
	ListChalanis(ctx context.Context, arg ListChalanisParams) ([]ListChalanisRow, error)
	// Complex queries with filtering
	ListDartas(ctx context.Context, arg ListDartasParams) ([]ListDartasRow, error)
	ListRecipients(ctx context.Context, arg ListRecipientsParams) ([]Recipient, error)
	MarkChalaniDelivered(ctx context.Context, arg MarkChalaniDeliveredParams) (Chalani, error)
	RemoveAllDartaAnnexes(ctx context.Context, dartaID pgtype.UUID) error
	RemoveAllDartaRelationships(ctx context.Context, dartaID pgtype.UUID) error
	RemoveChalaniAttachment(ctx context.Context, arg RemoveChalaniAttachmentParams) error
	RemoveChalaniSignatory(ctx context.Context, id uuid.UUID) error
	RemoveDartaAnnex(ctx context.Context, arg RemoveDartaAnnexParams) error
	RemoveDartaRelationship(ctx context.Context, arg RemoveDartaRelationshipParams) error
	UpdateApplicant(ctx context.Context, arg UpdateApplicantParams) (Applicant, error)
	UpdateChalaniAcknowledgement(ctx context.Context, arg UpdateChalaniAcknowledgementParams) (Chalani, error)
	UpdateChalaniApprovalStatus(ctx context.Context, arg UpdateChalaniApprovalStatusParams) (Chalani, error)
	UpdateChalaniDispatch(ctx context.Context, arg UpdateChalaniDispatchParams) (Chalani, error)
	UpdateChalaniNumber(ctx context.Context, arg UpdateChalaniNumberParams) (Chalani, error)
	UpdateChalaniStatus(ctx context.Context, arg UpdateChalaniStatusParams) (Chalani, error)
	UpdateChalaniTemplate(ctx context.Context, arg UpdateChalaniTemplateParams) (ChalaniTemplate, error)
	UpdateDartaAssignment(ctx context.Context, arg UpdateDartaAssignmentParams) (Darta, error)
	UpdateDartaClassification(ctx context.Context, arg UpdateDartaClassificationParams) (Darta, error)
	UpdateDartaMetadata(ctx context.Context, arg UpdateDartaMetadataParams) (Darta, error)
	UpdateDartaNumber(ctx context.Context, arg UpdateDartaNumberParams) (Darta, error)
	UpdateDartaStatus(ctx context.Context, arg UpdateDartaStatusParams) (Darta, error)
	UpdateRecipient(ctx context.Context, arg UpdateRecipientParams) (Recipient, error)
	VoidChalani(ctx context.Context, id uuid.UUID) (Chalani, error)
	VoidDarta(ctx context.Context, id uuid.UUID) (Darta, error)
}

var _ Querier = (*Queries)(nil)
