import { uuid, nowISO } from "../utils";

const createUser = (id: string, username: string, fullName: string) => ({
  __typename: "User" as const,
  id,
  username,
  fullName,
  email: null,
  phone: null,
  roles: null,
  createdAt: null,
  updatedAt: null,
});

const createWard = (id: string, name: string, number: number) => ({
  __typename: "Ward" as const,
  id,
  name,
  number,
  localBodyId: "LB-001",
  localBodyName: "Test Municipality",
  districtId: null,
  provinceId: null,
  createdAt: null,
  updatedAt: null,
});

export const chalaniSeeds = [
  // 🟢 1. Draft
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: null,
    formattedChalaniNumber: null,
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: createWard("W-5", "Ward No. 5", 5),
    subject: "Land Ownership Certificate – Draft",
    body: "Draft of outgoing letter regarding land ownership certification.",
    templateId: null,
    attachments: [],
    linkedDarta: null,
    status: "DRAFT" as const,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: false,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-001",
      type: "GOVERNMENT_OFFICE" as const,
      name: "District Land Office",
      organization: "Land Revenue Department",
      email: "district.land@gov.np",
      phone: "9851000001",
      address: "Nepalgunj",
    },
    createdBy: createUser("U-CLERK", "clerk", "Mock Clerk"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["SUBMIT" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟡 2. Pending Review
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: null,
    formattedChalaniNumber: null,
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: createWard("W-5", "Ward No. 5", 5),
    subject: "Infrastructure Plan – Review Pending",
    body: "Letter awaiting review for new infrastructure project.",
    templateId: null,
    status: "PENDING_REVIEW" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: false,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-002",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Municipal Engineering Division",
      organization: "Municipal Office",
      email: null,
      phone: null,
      address: "Birendranagar",
    },
    createdBy: createUser("U-CLERK", "clerk", "Mock Clerk"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["EDIT_REQUIRED" as const, "APPROVE_REVIEW" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟠 3. Pending Approval
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: null,
    formattedChalaniNumber: null,
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: createWard("W-2", "Ward No. 2", 2),
    subject: "Water Supply Proposal – Awaiting Approval",
    body: "Reviewed proposal awaiting CAO approval.",
    templateId: null,
    status: "PENDING_APPROVAL" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: false,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-003",
      type: "ORGANIZATION" as const,
      name: "Water Board",
      organization: null,
      email: null,
      phone: null,
      address: "Kohalpur",
    },
    createdBy: createUser("U-REVIEWER", "reviewer", "Ward Secretary"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: [
      "APPROVE" as const,
      "REJECT" as const,
      "RESERVE_NO" as const,
    ],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🔵 4. Number Reserved
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 45,
    formattedChalaniNumber: "45/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Official Invitation – Number Reserved",
    body: "Official invitation letter with reserved number.",
    templateId: null,
    status: "NUMBER_RESERVED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-004",
      type: "CITIZEN" as const,
      name: "Mr. Ramesh KC",
      organization: null,
      email: null,
      phone: null,
      address: "Kailali",
    },
    createdBy: createUser("U-APPROVER", "cao", "CAO"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["FINALIZE" as const, "VOID" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🔵 5. Registered
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 56,
    formattedChalaniNumber: "56/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Birth Certificate – Registered",
    body: "Official outgoing letter registered in ledger.",
    templateId: null,
    status: "REGISTERED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-005",
      type: "CITIZEN" as const,
      name: "Ms. Sita Thapa",
      organization: null,
      email: null,
      phone: null,
      address: "Surkhet",
    },
    createdBy: createUser("U-CLERK", "clerk", "Clerk"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["SIGN" as const, "VOID" as const, "DISPATCH" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟣 6. Signed
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 67,
    formattedChalaniNumber: "67/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Scholarship Approval – Signed",
    body: "Scholarship approval letter signed by authorized officer.",
    templateId: null,
    status: "SIGNED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-006",
      type: "ORGANIZATION" as const,
      name: "Education Office",
      organization: null,
      email: null,
      phone: null,
      address: "Nepalgunj",
    },
    createdBy: createUser("U-SIGNATORY", "signatory", "Authorized Officer"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["SEAL" as const, "DISPATCH" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟣 7. Sealed
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 78,
    formattedChalaniNumber: "78/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Audit Response – Sealed",
    body: "Response to audit query, sealed and ready for dispatch.",
    templateId: null,
    status: "SEALED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-007",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Audit Office",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-SIGNATORY", "signatory", "Authorized Officer"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["DISPATCH" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟤 8. Dispatched
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 89,
    formattedChalaniNumber: "89/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Notice to Ministry – Dispatched",
    body: "Official notice dispatched via postal service.",
    templateId: null,
    status: "DISPATCHED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: "POSTAL" as const,
    dispatchedAt: nowISO(),
    dispatchedBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    trackingId: "POST-00123",
    courierName: "Nepal Post",
    recipient: {
      __typename: "Recipient" as const,
      id: "R-008",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Ministry of Federal Affairs",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["MARK_IN_TRANSIT" as const, "ACKNOWLEDGE" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟤 9. In Transit
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 98,
    formattedChalaniNumber: "98/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Citizen Charter – In Transit",
    body: "Citizen charter document in transit to ministry.",
    templateId: null,
    status: "IN_TRANSIT" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: "POSTAL" as const,
    dispatchedAt: nowISO(),
    dispatchedBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    trackingId: "TRACK-998",
    courierName: "Nepal Post",
    recipient: {
      __typename: "Recipient" as const,
      id: "R-009",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Ministry of Local Dev",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["DELIVER" as const, "RETURN_UNDELIVERED" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // 🟤 10. Delivered
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 107,
    formattedChalaniNumber: "107/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Budget Circular – Delivered",
    body: "Annual budget circular delivered to finance division.",
    templateId: null,
    status: "DELIVERED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: "POSTAL" as const,
    dispatchedAt: nowISO(),
    dispatchedBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    trackingId: "POST-107",
    courierName: "Nepal Post",
    deliveredAt: nowISO(),
    deliveredProof: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-010",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Finance Division",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-CLERK", "clerk", "Clerk"),
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["CLOSE" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // ⚫ 11. Closed
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 32,
    formattedChalaniNumber: "32/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Archived Notice – Closed",
    body: "Notice archived and closed after successful delivery.",
    templateId: null,
    status: "CLOSED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: "POSTAL" as const,
    dispatchedAt: nowISO(),
    dispatchedBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    trackingId: "POST-032",
    courierName: "Nepal Post",
    deliveredAt: nowISO(),
    deliveredProof: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-011",
      type: "CITIZEN" as const,
      name: "Mr. Hari Prasad",
      organization: null,
      email: null,
      phone: null,
      address: "Nepalgunj",
    },
    createdBy: createUser("U-CLERK", "clerk", "Clerk"),
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: [],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // ⚫ 12. Voided
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 23,
    formattedChalaniNumber: "23/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Erroneous Entry – Voided",
    body: "Entry voided due to incorrect recipient information.",
    templateId: null,
    status: "VOIDED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: false,
    dispatchChannel: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-012",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Office of the Auditor General",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-CLERK", "clerk", "Clerk"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: [],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // ⚫ 13. Superseded
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 15,
    formattedChalaniNumber: "15/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Policy Revision – Superseded",
    body: "Policy document superseded by newer version.",
    templateId: null,
    status: "SUPERSEDED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: false,
    dispatchChannel: null,
    supersedesId: "some-old-id",
    recipient: {
      __typename: "Recipient" as const,
      id: "R-013",
      type: "GOVERNMENT_OFFICE" as const,
      name: "Policy Division",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-CAO", "cao", "CAO"),
    dispatchedAt: null,
    dispatchedBy: null,
    trackingId: null,
    courierName: null,
    isAcknowledged: false,
    acknowledgedAt: null,
    acknowledgedBy: null,
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    auditTrail: [],
    supersededById: null,
    allowedActions: [],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },

  // ⚫ 14. Acknowledged
  {
    __typename: "Chalani" as const,
    id: uuid(),
    chalaniNumber: 150,
    formattedChalaniNumber: "150/2081-82",
    fiscalYear: "2081/82",
    scope: "MUNICIPALITY" as const,
    ward: null,
    subject: "Digital Chalani – Acknowledged",
    body: "Digital chalani acknowledged by recipient via portal.",
    templateId: null,
    status: "ACKNOWLEDGED" as const,
    attachments: [],
    linkedDarta: null,
    requiredSignatories: [],
    approvals: [],
    isFullyApproved: true,
    dispatchChannel: "EDARTA_PORTAL" as const,
    dispatchedAt: nowISO(),
    dispatchedBy: createUser("U-DISPATCH", "dispatch", "Dispatch Officer"),
    trackingId: "DIGITAL-150",
    courierName: null,
    isAcknowledged: true,
    acknowledgedAt: nowISO(),
    acknowledgedBy: "Digital Recipient",
    acknowledgementProof: null,
    deliveredAt: null,
    deliveredProof: null,
    recipient: {
      __typename: "Recipient" as const,
      id: "R-014",
      type: "GOVERNMENT_OFFICE" as const,
      name: "e-Palika Portal",
      organization: null,
      email: null,
      phone: null,
      address: "Kathmandu",
    },
    createdBy: createUser("U-CLERK", "clerk", "Clerk"),
    auditTrail: [],
    supersededById: null,
    supersedesId: null,
    allowedActions: ["DELIVER" as const],
    createdAt: nowISO(),
    updatedAt: nowISO(),
  },
];
