apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: epalika-dev

namespace: epalika-dev

bases:
- ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
- namespace-patch.yaml
- replica-patch.yaml
- resources-patch.yaml
- ingress-patch.yaml

configMapGenerator:
- name: epalika-config-dev
  literals:
  - fga-check-url=http://openfga:8080/stores/$(FGA_STORE)/check
  - keycloak-url=http://keycloak:8083
  - keycloak-realm=epalika-dev
  - environment=development
  - log-level=debug

secretGenerator:
- name: epalika-secrets-dev
  literals:
  - fga-store-id=dev-store-id
  - fga-model-id=dev-model-id
  - keycloak-client-secret=dev-gateway-secret

images:
- name: epalika/pdp
  newTag: dev-latest
- name: epalika/darta-chalani
  newTag: dev-latest